config/routes.rb
IceCreamApp::Application.routes.draw do
  resources :icecreams
  get "sessions/new", :as => :new_session
  post "sessions/create", :as => :sessions
  delete "logout" => 'sessions#destroy', :as => :logout
end

app/models/icecream.rb
class Icecream < ActiveRecord::Base
  attr_accessible :name, :price, :image, :remote_image_url
  validates :name, presence: true, uniqueness: true
  validates :price, presence: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :login, :password_confirmation
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :find_user
  
  def find_user
    @user = User.find_by_id(session[:user_id]) #session[:login_id] only exists if valid session created
  end

  def require_login
    if @user.blank?
      redirect_to icecreams_url, notice: "You must be logged in!"
    end
  end
  
end

app/controllers/icecreams_controller.rb
class IcecreamsController < ApplicationController
  
  before_filter :require_login, :only => [:new, :create, :edit, :destroy]
  
  def index
    @icecream = Icecream.all
  end
  
  def new
    @icecream = Icecream.new
  end
  
  def create
    @icecream = Icecream.new(params[:icecream])
    
    if @icecream.save
      flash[:notice] = "New Ice Cream Added!"
      redirect_to icecreams_path 
    else
      flash[:alert] = "Something went wrong, try again!"
      render :new
    end
  end
  
  def show
    @icecream = Icecream.find(params[:id])
  end
  
  def edit
    @icecream = Icecream.find(params[:id])
  end
  
  def update
    @icecream = Icecream.find(params[:id])
    @icecream.update_attributes(params[:icecream])
    @icecream.save
    
    if @icecream.save
      flash[:notice] = "New Ice Cream Added!"
      redirect_to icecreams_path 
    else
      flash[:alert] = "Something went wrong, try again!"
      render :edit
    end
  end
  
  def destroy
    @icecream = Icecream.find(params[:id])
    @icecream.destroy
    redirect_to icecreams_path
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_login(params[:login])
    if user
      if user.authenticate(params[:password])
        flash[:notice] = "Hello, #{user.name}!"
        session[:user_id] = user.id
        redirect_to icecreams_path
      else
        flash[:notice] = "Wrong Password"
        redirect_to icecreams_path
      end
    else
      flash[:notice] = "Unknown Login"
      redirect_to icecreams_path
    end 
  end

  def destroy
    reset_session
    redirect_to icecreams_url, notice: "See ya!"
  end
end

# Add gem bcrypt (gives us authenticate method) + need to have a password_digest column in database
# Add has_secure_password to User model
# Create a 'sessions' controller with new, create, destroy
# Create routes

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/icecreams_helper.rb
module IcecreamsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/icecreams/edit.html.erb
<h1>Editing listing: <%= @icecream.name %></h1>

<%= form_for @icecream, html: { multipart: true } do |icecream| %>
	<%= icecream.label :name %>
	<%= icecream.text_field :name %>
	<p>
	<%= icecream.label :price %>
	<%= icecream.text_field :price %>
	</p>
	<%= icecream.file_field :image %>
	<p>
	<%= icecream.submit "Update Flavor!"%>
	</p>
<% end %>

app/views/icecreams/index.html.erb
<h1>Ice Cream For Sale!</h1>
<p>
	This is a list of our ice creams:
</p>

<% if @icecream.empty? %>
	<%= "We currently do not have any ice cream for sale." %>
<% end %>	
	
<% @icecream.each do |x| %>
	<%= image_tag x.image_url(:thumb).to_s %>
	<%= link_to x.name, x %>
	$<%= x.price %>
<% end %>	

<br></br>
<%= link_to "Add a Flavor", new_icecream_path %>

app/views/icecreams/new.html.erb
<h1>Add a new flavor</h1>

<%= form_for @icecream, html: { multipart: true } do |icecream| %> 
	<%= icecream.label :name %>
	<%= icecream.text_field :name %>
	<p>
		<%= icecream.label :price %>
		<%= icecream.text_field :price %>
	</p>
	<p>
		<%= icecream.file_field :image %>
	</p>
	<p>
		<%= icecream.label :remote_image_url, "or image URL" %>
		<%= icecream.text_field :remote_image_url %>
	</p>
		<%= icecream.submit "Add Flavor!"%>
<% end %>

<%= link_to "Home", icecreams_path %>

app/views/icecreams/show.html.erb
<h1>Listing for <%= @icecream.name %></h1>
<p>
	Price: $<%= @icecream.price%>
</p>

<% if @user %>	
	<%= link_to "Edit", edit_icecream_path %>
	<%= link_to "Delete", icecream_path(@icecream.id), method: 'delete', confirm: "Are you sure?" %>
<% end %>

<%= link_to "Home", icecreams_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IceCreamApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
<% if @user %>
	<p>Hello, <%= @user.name %>
		<%= link_to "Logout", logout_url, :method => :delete %>
		</p>
<% else %>
	<%= link_to "Login", new_session_url %>
<% end %>
	
<% if flash[:alert].present? %>
	<p style="color: white; background: red; padding: 6px"><%= flash[:alert] %></p>
	
	<% @icecream.errors.full_messages.each do |msg| %>
		<ul>
		<li><%= msg %></li>
		</ul>
	<% end %>
	
<% elsif flash[:notice].present? %>
	<p style="color: white; background:green; padding: 6px"><%= flash[:notice] %></p>
<% end %>


<%= yield %>

</body>
</html>